export const GET_WORKOUT_LIST_REQUESTED = 'GET_WORKOUT_LIST_REQUESTED';
export const GET_WORKOUT_LIST_SUCCESS = 'GET_WORKOUT_LIST_SUCCESS';
export const GET_WORKOUT_LIST_FAIL = 'GET_WORKOUT_LIST_FAIL';




export const WORKOUT_DETAILS_REQUESTED = 'WORKOUT_DETAILS_REQUESTED';
export const WORKOUT_DETAILS_SUCCESS = 'WORKOUT_DETAILS_SUCCESS';
export const WORKOUT_DETAILS_FAIL = 'WORKOUT_DETAILS_FAIL';




export const SET_WORKOUT_LIST_ITEM = 'SET_WORKOUT_LIST_ITEM';
export const SET_EXERSISE_ID = 'SET_EXERSISE_ID';
export const SET_EXERSISE_PLAY_VIDEO = 'SET_EXERSISE_PLAY_VIDEO';
export const IS_STATUS_BAR = 'IS_STATUS_BAR';


