export const SHOP_CATEGORIES_LIST_REQUESTED = 'SHOP_CATEGORIES_LIST_REQUESTED';
export const SHOP_CATEGORIES_LIST_SUCCESS = 'SHOP_CATEGORIES_LIST_SUCCESS';
export const SHOP_CATEGORIES_LIST_FAIL = 'SHOP_CATEGORIES_LIST_FAIL';

export const ADD_TO_CART_REQUESTED = 'ADD_TO_CART_REQUESTED';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const GET_CART_REQUESTED = 'GET_CART_REQUESTED';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';

export const SET_PRODUCT_DETAILS_TO_ADD_IN_CART =
  'SET_PRODUCT_DETAILS_TO_ADD_IN_CART';
