export const VIEW_ALL_BLOG_REQUESTED = 'VIEW_ALL_BLOG_REQUESTED';
export const VIEW_ALL_BLOG_SUCCESS = 'VIEW_ALL_BLOG_SUCCESS';
export const VIEW_ALL_BLOG_FAIL = 'VIEW_ALL_BLOG_FAIL';


export const SET_BLOG_ID = 'SET_BLOG_ID';


