export const USER_DETAILS_REQUESTED = 'USER_DETAILS_REQUESTED';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const ACCOUNT_REQUESTED = 'ACCOUNT_REQUESTED';
export const ACCOUNT_SUCCESS = 'ACCOUNT_SUCCESS';
export const ACCOUNT_FAIL = 'ACCOUNT_FAIL';

export const PERSONAL_DATA_REQUESTED = 'PERSONAL_DATA_REQUESTED';
export const PERSONAL_DATA_SUCCESS = 'PERSONAL_DATA_SUCCESS';
export const PERSONAL_DATA_FAIL = 'PERSONAL_DATA_FAIL';

export const GET_ADDRESS_LIST_REQUESTED = 'GET_ADDRESS_LIST_REQUESTED';
export const GET_ADDRESS_LIST_SUCCESS = 'GET_ADDRESS_LIST_SUCCESS';
export const GET_ADDRESS_LIST_FAIL = 'GET_ADDRESS_LIST_FAIL';


export const GET_CARD_LIST_REQUESTED = 'GET_CARD_LIST_REQUESTED';
export const GET_CARD_LIST_SUCCESS = 'GET_CARD_LIST_SUCCESS';
export const GET_CARD_LIST_FAIL = 'GET_CARD_LIST_FAIL';

