export const HIT_STEPS = 'HIT_STEPS';
export const HIT_STEPS_SUCCESS = 'HIT_STEPS_SUCCESS';
export const HIT_STEPS_FAILEED = 'HIT_STEPS_FAILEED';

export const SET_STEPS = 'SET_STEPS';

export const ADD_GLASS_REQUESTED = 'ADD_GLASS_REQUESTED';
export const ADD_GLASS_SUCCESS = 'ADD_GLASS_SUCCESS';
export const ADD_GLASS_FAIL = 'ADD_GLASS_FAIL';

export const GET_WATER_GLASS_REQUESTED = 'GET_WATER_GLASS_REQUESTED';
export const GET_WATER_GLASS_SUCCESS = 'GET_WATER_GLASS_SUCCESS';
export const GET_WATER_GLASS_FAIL = 'GET_WATER_GLASS_FAIL';

export const GET_HOME_REQUESTED = 'GET_HOME_REQUESTED';
export const GET_HOME_SUCCESS = 'GET_HOME_SUCCESS';
export const GET_HOME_FAIL = 'GET_HOME_FAIL';
