export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// MY CODE
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
// MY CODE

export const FORGOT_PASS_REQUESTED = 'FORGOT_PASS_REQUESTED';
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS';
export const FORGOT_PASS_FAIL = 'FORGOT_PASS_FAIL';

export const OTP_VERIFICATION_REQUESTED = 'OTP_VERIFICATION_REQUESTED';
export const OTP_VERIFICATION_SUCCESS = 'OTP_VERIFICATION_SUCCESS';
export const OTP_VERIFICATION_FAIL = 'OTP_VERIFICATION_FAIL';

export const RESET_PASSWORD_REQUESTED = 'RESET_PASSWORD_REQUESTED';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const CONTACT_SUPPORT_REQUESTED = 'CONTACT_SUPPORT_REQUESTED';
export const CONTACT_SUPPORT_SUCCESS = 'CONTACT_SUPPORT_SUCCESS';
export const CONTACT_SUPPORT_FAIL = 'CONTACT_SUPPORT_FAIL';

export const DEVICE_TOKEN_REQUESTED = 'DEVICE_TOKEN_REQUESTED';
export const DEVICE_TOKEN_SUCCESS = 'DEVICE_TOKEN_SUCCESS';
export const DEVICE_TOKEN_FAIL = 'DEVICE_TOKEN_FAIL';
